{
 "title": "Line Overview",
 "tags": [ "Line Level" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "LINE INFO",
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "# Marcio Mourao\n\nProcess Coach ext 311\n\n# Lucas Heath\n\nTeam Lead ext 572\n\n# Paypoint\n\nStation 190"
   }
  },
  {
   "title": "TOTAL PARTS PER HOUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize count() by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize sum(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Bad", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e15152f2-4a08-48c9-a01f-168960fb1970",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize sum(Units_Bad) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "AVERAGE HOURLY GOOD PARTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize avg(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "QUALITY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "" }, "property": { "name": "", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "quality": "GOOD",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize sum(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "" }, "property": { "name": "", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "quality": "GOOD",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "TOTAL UNITS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Total", "type": "number" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Production Is",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "JPH_Target", "type": "number" }, "type": "groupBy" },
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| summarize by bin(Timestamp, 1m), JPH_Target\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "TARGET UNITS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "JPH_Target", "type": "number" }, "type": "groupBy" },
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a780597d-b9e5-4e33-830f-ef2797dd568b",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| summarize by bin(Timestamp, 1m), JPH_Target\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Total", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| summarize sum(Units_Total) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "JPH_Target", "type": "number" }, "type": "groupBy" },
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a780597d-b9e5-4e33-830f-ef2797dd568b",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| summarize by bin(Timestamp, 1m), JPH_Target / 60\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 16 },
   "options": {
    "content": "<p>&nbsp;</p>\n\n\n# &nbsp;&nbsp;&nbsp;    **Station State**\n\n"
   }
  },
  {
   "title": "STA 110",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 110", "name": "==", "value": "Station 110" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 120",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "a5b3677e-7e51-46bf-a1d6-0bdaa92d092d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 120", "name": "==", "value": "Station 120" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 120'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 130",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 140",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 140", "name": "==", "value": "Station 140" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 140'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 150",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 150", "name": "==", "value": "Station 150" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 150'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 160",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 160", "name": "==", "value": "Station 160" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 160'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 170",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 170", "name": "==", "value": "Station 170" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 170'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 180",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STATION 190",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 190", "name": "==", "value": "Station 190" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 190'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}