{
 "title": "Station Production",
 "time": { "from": "now-1h", "to": "now-0m" },
 "templating": {
  "list": [
   { "name": "AssetID", "label": "Asset ID", "query": "Units\n| project Device_Alias" }
  ]
 },
 "panels": [
  { "title": "$AssetID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "AssetID" },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 } },
  {
   "title": "QUALITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Good", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "quality": "GOOD",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Good > 0\n| summarize sum(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "quality": "GOOD",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 2, "x": 4, "y": 3 } },
  {
   "title": "Total Parts",
   "type": "gauge",
   "description": "Gauge Readout = Total Units.   \nGauge Maximum = Target Units ",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a780597d-b9e5-4e33-830f-ef2797dd568b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Total", "type": "number" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Total Good Parts",
   "type": "gauge",
   "description": "Gauge Readout = Total Units.   \nGauge Maximum = Target Units ",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Good", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Good > 0\n| summarize sum(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a780597d-b9e5-4e33-830f-ef2797dd568b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Total Reject Parts",
   "type": "gauge",
   "description": "Gauge Readout = Total Units.   \nGauge Maximum = Target Units ",
   "gridPos": { "h": 9, "w": 5, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Bad", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Bad", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e15152f2-4a08-48c9-a01f-168960fb1970",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Bad > 0\n| summarize sum(Units_Bad) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Units_Total", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), Units_Total\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "AVERAGE HOURLY GOOD PARTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Good", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Good > 0\n| summarize avg(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 12 } },
  {
   "title": "TOTAL PARTS PER HOUR",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ede35ca6-71fc-415a-bdc5-574ed55cbe2b",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Good", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Good", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7e425373-e2bb-44aa-9e26-0a87dd33d3db",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Good > 0\n| summarize sum(Units_Good) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "Units", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Units_Bad", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": ">", "value": 0 }, "property": { "name": "Units_Bad", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e15152f2-4a08-48c9-a01f-168960fb1970",
     "query": "Units\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Units_Bad > 0\n| summarize sum(Units_Bad) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "1h",
     "timeOrdering": "ASCENDING"
    }
   ]
  }
 ]
}