version: '3'

services:
  db:
    build: db
    ports:
      - 5432:5432
      - 5666:5666
      - 5667:5667
  web:
    build: web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  nagios:
    build: nagios
    ports:
      - 8090:80
      - 25:25
    depends_on:
      - db
