apiVersion: v1
kind: Pod
metadata:
  name: "ldap"
  labels:
    service: ldap
    name: "devops"
  namespace: "devops"
spec:
  volumes:
  - name: "ldap-db"
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /ldap_db/_data
  - name: "ldap-static"
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /ldap_static/_data
  containers:
  - name: ldap
    image: accenture/adop-ldap:0.1.3
    env:
    - name: "INITIAL_ADMIN_USER"
      value: "digitalonus"
    - name: "INITIAL_ADMIN_PASSWORD"
      value: "YWQxdGF6ejAx"
    - name: "JENKINS_PASSWORD"
      value: "MWE1M2FiMWM4Yzc2OTUzOA=="
    - name: "GERRIT_PASSWORD"
      value: "NzUyZWJiZGEwMGE5Mzk5Mg=="
    - name: "SLAPD_PASSWORD"
      value: "e5fdb71de4379485"
    - name: "SLAPD_DOMAIN"
      value: "ldap.example.com"
    - name: "SLAPD_FULL_DOMAIN"
      value: "dc=ldap,dc=example,dc=com"
    ports:
    - name: ldap-admin
      containerPort: 389
    volumeMounts:
    - name: "ldap-db"
      mountPath: "/var/lib/ldap"
    - name: "ldap-static"
      mountPath: "/etc/ldap"


