#-----------------------------------------------------------------------------------------------------------------
# Example configuration for orca to override the docker image.
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    service-settings:
      orca:
        artifactId: armory/orca-armory:2022.04.27.06.17.06.release-2.27.x
