---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        description: prevents giant files from being committed.
        args: [--maxkb=1024]
      - id: mixed-line-ending
        description: replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: trailing-whitespace
        description: trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
        description: detects the presence of private keys.
        exclude: .gitleaks.toml
      - id: check-merge-conflict
        description: checks for files that contain merge conflict strings.
      - id: fix-byte-order-marker
        description: removes utf-8 byte order marker.
      - id: check-case-conflict
        description: |
          checks for files that would conflict in case-insensitive filesystems.
      - id: check-executables-have-shebangs
        description: ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable
        description: |
          ensures that (non-binary) files with a shebang are executable
      - id: check-symlinks
        description: checks for symlinks which do not point to anything.
      - id: destroyed-symlinks
        description: |
          detects symlinks which are changed to regular files with a content of
          a path which that symlink was pointing to.
      - id: end-of-file-fixer
        description: |
          ensures that a file is either empty, or ends with one newline.
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: .*docker-compose.*|.*gitlab-ci.*
        args: [--allow-multiple-documents]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
        description: |
          Rewrites all Terraform configuration files to a canonical format.
      - id: terraform_validate
        description: Validates all Terraform configuration files.
      - id: terraform_tflint
        description: Validates all Terraform configuration files with TFLint.
      - id: terraform_tfsec
        description: |
          Static analysis of Terraform templates to spot potential security
          issues.
      - id: checkov
        name: Checkov
        description: Runs checkov on Terraform templates.
        verbose: true
        args: [-d, ., --skip-check, CKV_DOCKER_2, --quiet]
        language: python
        pass_filenames: false
        always_run: false
        files: \.tf$
        exclude: \.terraform\/.*$
        require_serial: true
      - id: terrascan
        name: terrascan
        description: Runs terrascan on Terraform templates.
        language: script
        entry: /usr/local/bin/terrascan scan -d ./ --non-recursive -i terraform
        files: \.tf$
        exclude: \.terraform\/.*$
        require_serial: true
  # pre-commit install --install-hooks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
        name: Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        language_version: system
        name: Lint markdown Documents

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shfmt
        name: Check shell style with shfmt
      - id: shellcheck
        name: Shell scripts conform to shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        exclude: CHANGELOG.md
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
      - id: gitleaks
        description: Detect hardcoded secrets using Gitleaks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        description: Lint git commit messages.
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        exclude: .*docker-compose.*|.*gitlab-ci.yml
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: .*docker-compose.*|.*gitlab-ci.yml
        args: [--format, parsable, --strict]
