---
- hosts: vault
  become: true
  user: ubuntu
  vars:
    service: vault
    datadog_process_checks:
      - { name: vault, search_string: ['vault'] }
  roles:
    - common
    - { role: filebeat, version: 6.4.0}
    - { role: datadog-agent }
    - { role: consul, config_file: consul_agent, cli: false}
    - vault
