---
kind: Service
apiVersion: v1
metadata:
  name: gerrit-mysql
  creationTimestamp: 
  labels:
    service: gerrit-mysql
  namespace: devops
spec:
  ports:
  - name: '3306'
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    service: gerrit-mysql

