---
kind: Service
apiVersion: v1
metadata:
  name: ldap-ltb
  creationTimestamp:
  labels:
    service: ldap-ltb
  namespace: devops
spec:
  ports:
  - name: '80'
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    service: ldap-ltb
