---
kind: Service
apiVersion: v1
metadata:
  name: nexus
  creationTimestamp: 
  labels:
    service: nexus
  namespace: devops
spec:
  ports:
  - name: '8081'
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    service: nexus
