---
kind: Service
apiVersion: v1
metadata:
  name: selenium-hub
  creationTimestamp: 
  labels:
    service: selenium-hub
  namespace: devops
spec:
  ports:
  - name: '4444'
    protocol: TCP
    port: 4444
    targetPort: 4444
  selector:
    service: selenium-hub
