{
 "title": "Shift Constraints",
 "tags": [ "Line Level" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 20, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "STA 110",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 110", "name": "==", "value": "Station 110" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 120",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "a5b3677e-7e51-46bf-a1d6-0bdaa92d092d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 120", "name": "==", "value": "Station 120" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 120'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 130",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 140",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 140", "name": "==", "value": "Station 140" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 140'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 150",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 150", "name": "==", "value": "Station 150" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 150'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 160",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 160", "name": "==", "value": "Station 160" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 160'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 170",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 170", "name": "==", "value": "Station 170" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 170'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 180",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "STA 190",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sub_State_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 190", "name": "==", "value": "Station 190" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ed4d5323-b88d-49a9-b83a-a47f099e52ba",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 190'\n| summarize by bin(Timestamp, 1m), Sub_State_Code\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Bottleneck_Rank", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 110", "name": "==", "value": "Station 110" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize by bin(Timestamp, 1m), Bottleneck_Rank\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a5b3677e-7e51-46bf-a1d6-0bdaa92d092d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Bottleneck_Rank", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize by bin(Timestamp, 1m), Bottleneck_Rank\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Bottleneck_Rank", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize by bin(Timestamp, 1m), Bottleneck_Rank\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bottleneck Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e1838b75-91e3-45bd-9810-c367f01db2fe",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 110", "name": "==", "value": "Station 110" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a5b3677e-7e51-46bf-a1d6-0bdaa92d092d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 120", "name": "==", "value": "Station 120" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 120'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 140", "name": "==", "value": "Station 140" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 140'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 150", "name": "==", "value": "Station 150" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 150'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 160", "name": "==", "value": "Station 160" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 160'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 170", "name": "==", "value": "Station 170" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 170'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sole Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Sole_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 190", "name": "==", "value": "Station 190" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "ef7805af-388b-4fbc-8662-1c2c3471d37c",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 190'\n| summarize by bin(Timestamp, 1m), Sole_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 110", "name": "==", "value": "Station 110" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a5b3677e-7e51-46bf-a1d6-0bdaa92d092d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 120", "name": "==", "value": "Station 120" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 120'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 140", "name": "==", "value": "Station 140" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 140'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 150", "name": "==", "value": "Station 150" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 150'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 160", "name": "==", "value": "Station 160" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 160'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 170", "name": "==", "value": "Station 170" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 170'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Shared Bottleneck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Shared_Bottleneck", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 190", "name": "==", "value": "Station 190" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "19caf0d0-abe4-4d03-9de4-c92a8a98d63a",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 190'\n| summarize by bin(Timestamp, 1m), Shared_Bottleneck\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "f9156e75-2f7f-4e93-9dc6-2613fa92357d",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "Station 110" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 110'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 120", "name": "==", "value": "Station 120" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 120'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "faef41e5-a5ea-41ec-8965-97700c63e60b",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 130", "name": "==", "value": "Station 130" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 130'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "a2a2b652-89ab-4c4f-a514-f1b3ca921ffa",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 140", "name": "==", "value": "Station 140" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 140'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "3d42874b-18c4-48fa-a082-f617d224b2fc",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 150", "name": "==", "value": "Station 150" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 150'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "6d093ed8-77a0-4c05-873b-d35a41171341",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 160", "name": "==", "value": "Station 160" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 160'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "75362c3a-0093-4773-a5d0-ccf493c182f4",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 170", "name": "==", "value": "Station 170" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 170'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "7de31965-43d7-431a-8d63-06c3fb1f0740",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 180", "name": "==", "value": "Station 180" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 180'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Mean Active Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "a10ccdc3-a7a1-4dff-be3d-f9c450731729",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "Station 190", "name": "==", "value": "Station 190" },
           "property": { "name": "Device_Alias", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e93e6663-71b3-450d-9eb8-a564a7d2af33",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == 'Station 190'\n| summarize avg(State_Cycling) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}