{
 "title": "Station Events",
 "tags": [
  "Station",
  "Events"
 ],
 "time": { "from": "now-1h", "to": "now-0m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "AssetID", "label": "Asset ID", "query": "JPH\n| project Device_Alias" }
  ]
 },
 "panels": [
  { "title": "$AssetID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "AssetID" },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Net_Available", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Net_Available", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "fbb97ff3-1c75-4bc5-b786-efacb4a6503e",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Net_Available == true\n| summarize sum(State_Net_Available) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Unplanned_Down", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Unplanned_Down", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "3f22b9f2-4179-4d7a-b9d9-54a1f5df0fec",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Unplanned_Down == true\n| summarize sum(State_Unplanned_Down) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "MTBF",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Schedule_Is_Productive", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          { "operator": { "name": "==", "value": 1 }, "property": { "name": "Schedule_Is_Productive", "type": "number" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Schedule_Is_Productive == 1\n| summarize sum(Schedule_Is_Productive) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    },
    {
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Breakdown", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Breakdown", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Breakdown == true\n| summarize sum(State_Breakdown) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw"
    },
    {
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "State_Breakdown", "type": "boolean" }, "type": "groupBy" },
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), State_Breakdown\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "MTTR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Breakdown", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Breakdown", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a3250ae5-4c69-44a8-97f1-2dcf277f30f2",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Breakdown == true\n| summarize sum(State_Breakdown) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Breakdown", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "1bbc2df2-5a38-4c30-8b0e-547a6871a466",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Breakdown == true\n| summarize count() by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "raw",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Time Stopped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "$__timeInterval", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Stopped", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Stopped", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "071363d7-41e9-48e5-a69a-7ddf745b7fe5",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Stopped == true\n| summarize sum(State_Stopped) by bin(Timestamp, $__timeInterval)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Time Breakdown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "$__timeInterval", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Breakdown", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Breakdown", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "a3250ae5-4c69-44a8-97f1-2dcf277f30f2",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Breakdown == true\n| summarize sum(State_Breakdown) by bin(Timestamp, $__timeInterval)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Time Cycling",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "$__timeInterval", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "State_Cycling", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "State_Cycling", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "b24031d9-9282-4278-829f-4342b213a5cf",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where State_Cycling == true\n| summarize sum(State_Cycling) by bin(Timestamp, $__timeInterval)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Station Events",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Event_Code", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "9d7047c6-9ba9-491e-955a-b4a84ed30c81",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Event_Code\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    },
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "StateCode", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Event_Desc", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "f36a36f5-e631-447a-881a-9a1c7b6af395",
     "query": "StateCode\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Event_Desc\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  }
 ]
}