{
 "title": "Station Cycle Times",
 "tags": [
  "Station",
  "CycleTimes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "AssetID", "label": "Asset ID", "query": "JPH\n| project Device_Alias" }
  ]
 },
 "panels": [
  { "title": "$AssetID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "AssetID" },
  {
   "title": "Performance Efficiency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregates": [ "AVERAGE" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "df788d08-ac60-47cd-a789-355924d80821",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize avg(Cycletime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Cycletime_Design_Target", "type": "number" }, "type": "groupBy" },
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Cycletime_Design_Target\n| order by Timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Cycle Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "AVERAGE" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Value", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "6e0a40b7-fa43-47e9-b3b4-187ddf3f1f50",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize count() by bin(Timestamp, 1m), Cycletime_Value\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Slow Cycle Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Slow", "type": "boolean" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "Cycletime_Slow", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "289331e8-132f-4cc3-8a24-5c851b2bdbd9",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Cycletime_Slow == true\n| summarize sum(Cycletime_Slow) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Invalid Cycle Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "Cycletime_Invalid", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "f9dbe2c7-f519-4dfd-af6e-4d317797282e",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Cycletime_Invalid == true\n| summarize count() by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Overcycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Overtime_Value", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "fad8a915-5d46-494f-af09-cba0bc613f80",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize sum(Cycletime_Overtime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Standard Cycle Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Value", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": false
           },
           "property": { "name": "Cycletime_Invalid", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e782804f-47f6-4cfd-8698-585f406a0e6b",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Cycletime_Invalid == false\n| summarize by bin(Timestamp, 1m), Cycletime_Value\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Min Cycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "min", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "6e0a40b7-fa43-47e9-b3b4-187ddf3f1f50",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize min(Cycletime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Avg Cycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "avg", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "6e0a40b7-fa43-47e9-b3b4-187ddf3f1f50",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize avg(Cycletime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Max Cycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregates": [ "AVERAGE" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "max", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "6e0a40b7-fa43-47e9-b3b4-187ddf3f1f50",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize max(Cycletime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Total Cycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregates": [ "SUM" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Cycletime_Value", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "b65b4af9-4daf-4560-b1b1-0f71a98f9dd6",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize sum(Cycletime_Value) by bin(Timestamp, 1m)\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    }
   ]
  },
  {
   "title": "Invalid Cycle Time ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Invalid_Target", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": {
            "name": "==",
            "value": true
           },
           "property": { "name": "Cycletime_Invalid", "type": "boolean" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7a10afb2-b4e5-4acf-a129-868f99367332",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| where Cycletime_Invalid == true\n| summarize by bin(Timestamp, 1m), Cycletime_Invalid_Target\n| order by Timestamp asc",
     "querySource": "visual"
    }
   ]
  },
  {
   "title": "Cycle Times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "aggregates": [ "AVERAGE" ],
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Value", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "6e0a40b7-fa43-47e9-b3b4-187ddf3f1f50",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Cycletime_Value\n| order by Timestamp asc",
     "querySource": "visual",
     "resolution": "AUTO",
     "timeOrdering": "ASCENDING"
    },
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Design_Target", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "e782804f-47f6-4cfd-8698-585f406a0e6b",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Cycletime_Design_Target\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    },
    {
     "assetId": "$AssetID",
     "database": "fiskustodatabase",
     "expression": {
      "from": { "property": { "name": "JPH", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1m", "type": "interval" }, "property": { "name": "Timestamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Cycletime_Invalid_Target", "type": "number" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$AssetID" }, "property": { "name": "Device_Alias", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "maxPageAggregations": 1,
     "propertyId": "7a10afb2-b4e5-4acf-a129-868f99367332",
     "query": "JPH\n| where $__timeFilter(Timestamp)\n| where Device_Alias == $AssetID\n| summarize by bin(Timestamp, 1m), Cycletime_Invalid_Target\n| order by Timestamp asc",
     "querySource": "visual",
     "timeOrdering": "ASCENDING"
    }
   ]
  }
 ]
}