# Generated by Django 3.0.8 on 2020-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('els', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueToChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_name', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
