server:
  port: 8081
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
