version: '3.1'
services:
  landing-backend:
    image: openhouselandingrest:latest
    build:
      context: .
    container_name: landing-backend
    ports:
    - 8080:8080
    depends_on:
    - landing-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://landing-db:5432/compose-postgres
    - SPRING_DATASOURCE_USERNAME=compose-postgres
    - SPRING_DATASOURCE_PASSWORD=compose-postgres
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - SPRING_JPA_SHOW_SQL=false
  landing-db:
    image: postgres:13.1-alpine
    ports:
    - 5432:5432
    container_name: landing-db
    environment:
    - POSTGRES_USER=compose-postgres
    - POSTGRES_PASSWORD=compose-postgres