version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
          - toolslocaldev_default
    webserver:
        image: 038131160342.dkr.ecr.us-east-1.amazonaws.com/airflow:0.0.37
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - CONSUL=consul
            - ENVIRONMENT=dev
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        networks:
          - toolslocaldev_default
        command: webserver
        networks:
          - toolslocaldev_default
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

networks:
  toolslocaldev_default:
    external:
      name: toolslocal-dev_default
