# Name of the workflow
name: Demo Workflow

on: [push]

jobs:
  how_you_dou_job:
    runs-on: ubuntu-latest
    name: A job to say how you dou'ing
    steps:

      # To use this repo's private action, must check out the repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: How you dou'ing world action step
        uses: ./ # Uses an action in the root directory
        id: hi
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hi` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hi.outputs.time }}"