AWSTemplateFormatVersion: '2010-09-09'
Description: 'FSx Module definition'
Parameters:
  ParameterVersion:
    Type: Number
    Description: 'Version'
  ParameterFSxStorageCapacity:
    Description: 'Enter the FSx storage capacity in GiB. Minimum 32 ; Maximum 65536 '
    Type: String
    Default: '32'
    AllowedPattern: "[+-]?(\\d+(\\.\\d+)?|\\.\\d+)([eE][+-]?\\d+)?"
  ParameterFSxStorageType:
    Type: String
    Default: SSD
    AllowedValues:
    - SSD
    - HDD
    Description: 'Select the FSx storage type. (NOTE: SINGLE_AZ_1 requires SSD.) Default:
      SSD'
  ParameterFSxName:
    Type: String
    Default: FSx
    AllowedPattern: "^[a-zA-Z0-9]+$"
    MinLength: '02'
    MaxLength: '32'
    Description: 'Enter a value for the tag Name. (Requirements: ALPHANUMERIC and
      between 2 and 32 characters.) Default: FSx01'
  ParameterSubnetIds:
      Type: List<String>
      Description: 'Subnet IDs that the file system will be accessible from. If your deployment type is MultiAZ you need to provide 2 subnets'
  ParameterPreferredSubnetId:
    Type: String
    Description: 'Preferred subnet id'
  ParameterSecurityGroupIds:
      Type: List<String>
      Description: 'SG for FSx'
  ParameterFSxThroughput:
    Type: String
    Default: '8'
    AllowedValues:
    - '8'
    - '16'
    - '32'
    - '64'
    - '128'
    - '256'
    - '512'
    - '512'
    - '1014'
    - '2048'
    Description: 'Select the FSx throughput capacity in MB/s. Default: 8 MB/s'
  ParameterDeployType:
    Type: String
    Default: SINGLE_AZ_2
    AllowedValues:
    - SINGLE_AZ_1
    - SINGLE_AZ_2
    - MULTI_AZ_1
    Description: 'Select the FSx deployment type. Default: SINGLE_AZ_2'
  ParameterADId:
    Type: String
    Description: 'Active Directory ID in which the FSx will join'
Resources:
  ResourceFsx:
    Type: AWS::FSx::FileSystem    
    Properties:
      FileSystemType: WINDOWS
      StorageCapacity:
        Ref: ParameterFSxStorageCapacity
      StorageType:
        Ref: ParameterFSxStorageType
      Tags:
      - Key: Name
        Value:
          Ref: ParameterFSxName
      - Key: "Version"
        Value:
          Ref: ParameterVersion
      SubnetIds:
          Ref: ParameterSubnetIds
      SecurityGroupIds:
      - Ref: ParameterSecurityGroupIds
      WindowsConfiguration:
        ThroughputCapacity:
          Ref: ParameterFSxThroughput
        DeploymentType:
          Ref: ParameterDeployType
        PreferredSubnetId: 
          Ref: ParameterPreferredSubnetId
        ActiveDirectoryId:
          Ref: ParameterADId
