#-----------------------------------------------------------------------------------------------------------------
# Example configuration for adding AWS accounts to spinnaker.
#
# Documentation: https://docs.armory.io/docs/spinnaker-install-admin-guides/add-aws-account/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:  
    config:
      providers:
        aws:
          enabled: true
          primaryAccount: aws-dou                # Must be one of the configured AWS accounts
          accounts:
          - name: aws-dou
            accountId: "439114917687"            # (Required). Your AWS account ID to manage. See the AWS IAM User Guide for more information.
            assumeRole: role/spinnakerManaged    # (Required). If set, will configure a credentials provider that uses AWS Security Token Service to assume the specified role. Example: “user/spinnaker” or “role/spinnakerManaged”
            lifecycleHooks: []                   # (Optional). Configuration for AWS Auto Scaling Lifecycle Hooks. For more information, see: https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html
            permissions: {}
            providerVersion: V1
            regions:                             # (Default: []). The AWS regions this Spinnaker account will manage.
            - name: us-west-2
          bakeryDefaults:                        # Configuration for Spinnaker’s image bakery.Configuration for Spinnaker’s image bakery.
            baseImages: []
          accessKeyId: AKIAWMPKJ443RQ2ZUDEA       # Only needed if cluster worker nodes don't have IAM roles for talking to the target aws account
          secretAccessKey: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.aws.secretAccessKey # Only needed if cluster worker nodes don't have IAM roles for talking to the target aws account
          defaultKeyPairTemplate: '{{"{{"}}name{{"}}"}}-keypair'
          defaultRegions:
          - name: us-west-2
          defaults:
            iamRole: BaseIAMRole
          features:
            cloudFormation:
              enabled: true                       # (Default: false). Enable cloudformation support on this AWS account.
        ecs:
          enabled: true
          accounts:
          - name: aws-dou-ecs
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            awsAccount: aws-dou                   # Must be one of the configured AWS accounts
          primaryAccount: aws-dou-ecs             # Must be one of the configured AWS ECS accounts

    # Only needed if spinnaker is not running in AWS and will deploy to AWS accounts
#    service-settings:
#      clouddriver:
#        env:
#          EC2_REGION: us-west-2
#      rosco:
#        env:
#          AWS_REGION: us-west-2
