version: 2.1
workflows:
    api:
      jobs:
          - "dependency_scan":
              context: CaaS
              filters:
                branches:
                  only:
                    - plm
          - "build":
              context: CaaS
              requires:
                - dependency_scan
              filters:
                  branches:
                      only:
                        - plm
          - "deploy":
              context: CaaS
              requires:
                  - build
              filters:
                  branches:
                      only:
                        - plm

jobs:
  "dependency_scan":
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Scan python dependencies for vulnerabilities
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user safety
            safety check -r requirements.txt
  "build":
    docker:
        - image: dockerdoufer/aws-docker:circleci0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Export environment variables
          command: |
            echo export $(grep -v '^#' dwarf.config | xargs) >> $BASH_ENV
      - run:
          name: Install DevOps repo
          command: |
            git clone -b $CI_VERSION https://${GITHUB_USER}:${GITHUB_TOKEN}@${GITHUB_URL_DEVOPS} ../devops.ci
      - run:
          name: Push image in ECR
          command: |
            env
            ls -la
            ls -la ..
            pwd
            chmod -R +x ../devops.ci/build_types
            ../devops.ci/build_types/docker_build.sh


  "deploy":
    docker:
        - image: dockerdoufer/aws-docker:circleci0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Export environment variables
          command: |
            echo export $(grep -v '^#' dwarf.config | xargs) >> $BASH_ENV
      - run:
          name: Install DevOps repo
          command: |
            env
            git clone -b $CI_VERSION https://${GITHUB_USER}:${GITHUB_TOKEN}@${GITHUB_URL_DEVOPS} ../devops.ci
      - run:
          name: Deploy container to development environment
          command: |
            chmod -R +x ../devops.ci
            ../devops.ci/deploy_type/deploy_supported_product_workload.sh
