---
- hosts: mule
  become: true
  user: ubuntu
  vars:
    service: mule
    datadog_process_checks:
      - { name: vault, search_string: ['mule'] }
  roles:
    - java
    - common
    - consul-template
    - datadog-java-client
    - { role: consul, config_file: consul_agent, cli: false}
    - { role: filebeat, version: 6.4.2, consul_template: true}
    - { role: datadog-agent }
    - { role: mule, version : 3.8.7-hf1 }
