apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iam-techmcne-com
spec:
  secretName: iam-techmcne-com-tls
  renewBefore: 240h
  dnsNames:
  - 'iam.techmcne.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer