apiVersion: v1
kind: Pod
metadata:
  name: "logstash"
  labels:
    service: "logstash"
    name: "devops"
  namespace: "devops"
spec:
  volumes:
  - name: "daas-logs"
    nfs:
     server: fs-7fe02cd6.efs.us-west-2.amazonaws.com
     path: /daas_logs
  imagePullSecrets:
  - name: regsecret
  containers:
  - name: logstash
    image: accenture/adop-logstash:0.1.0
    ports:
    - containerPort: 12201
      protocol: UDP
    - containerPort: 25826
      protocol: UDP
    - containerPort: 5000
      protocol: TCP
    env:
#    - name: 'constraint:tier'
#      value: '=public'
    - name: LS_HEAP_SIZE
      value: 1024m
    volumeMounts:
    - name: "daas-logs"
      mountPath: "/var/log/logstash/development/"
