node_image         = "ubuntu-os-cloud/ubuntu-1604-lts"
node_machine_type  = "n1-standard-4"
node_zone          = "us-central1-a"
node_network_id    = "node-network"
node_count         = "1"
node_owner = "hum"
ssh_key_name = "Hum_do"
