style: bitbucket
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://bitbucket.corp.internal.companyA.com/scm/clddo/tfe-aws-alb-asg-pattern.git
options:
  commits:
    filters:
      Type:
        - feat
        - test
        - update
    #     - perf
    #     - refactor
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
