AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secret Manager'
Parameters:
  ParameterVersion:
    Type: Number
    Description: 'Version'
  ParameterSecretName:
    Type: String
    Description: 'Name of the secret'
  ParameterSecretValue:
    Type: String
    Description: 'Secret that will be stored in the secret manager'
  ParameterSecretDescription:
    Type: String
    Description: 'Short description about the secret'
  ParameterSecretType:
    Type: String
    Description: 'simple or password'
Conditions:
  IsPassword:
    !Equals [!Ref ParameterSecretType, 'password'] 
  IsNotPassword:
    !Not [Condition: IsPassword]
Resources:
  ResourceSampleSecretManager:
    Condition: IsNotPassword
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Ref ParameterSecretDescription
      Name: !Ref ParameterSecretName
      SecretString: !Ref ParameterSecretValue
      Tags:
      - Key: "Version"
        Value:
          Ref: ParameterVersion
  ResourcePasswordSecretManager:
    Condition: IsPassword
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Ref ParameterSecretName
      Description: !Ref ParameterSecretDescription
      GenerateSecretString:
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
      - Key: "Version"
        Value:
          Ref: ParameterVersion
