---

- name: install java-openjdk11
  shell: amazon-linux-extras install java-openjdk11 -y

- name: install java-1.8.0-openjdk-devel
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: Download rpm package
  shell: curl -sL https://rpm.nodesource.com/setup_14.x | bash -

- name: install nodejs
  yum:
    name: nodejs
    state: latest
