#-----------------------------------------------------------------------------------------------------------------
# Example configuration for enabling terraformer stages in spinnaker
#
# Feature documentation: https://docs.armory.io/docs/spinnaker/terraform-use-integration/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # Docs: https://docs.armory.io/docs/spinnaker/terraform-enable-integration/
  spinnakerConfig:
    # Enables terraformer backend feature
    config:
      armory:
        terraform:
          enabled: true
      artifacts:
        # Gitrepo support, so that terraformer downloads terraform scripts from git repositories
        gitrepo:
          enabled: true
          accounts:
            - name: dou
              username: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.github.username # Git username.
              token: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.github.token # (Secret). Git token.
            - name: armory
              username: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.github.username # Git username.
              token: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.github.token # (Secret). Git token.
        github:
          enabled: true
          accounts:
            - name: dou
              username: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.github.username # Git username.
              token: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.github.token # (Secret). Git token.
            - name: armory
              username: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.github.username # Git username.
              token: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.github.token # (Secret). Git token.
#              password: xyz                    # (Secret). Git password.
#              tokenFile: token.txt             # (Secret). File containing a Git authentication token. File needs to be present on the machine running Spinnaker.
#              usernamePasswordFile: creds.txt  # (Secret). File containing “username:password” to use for GitHub authentication. File needs to be present on the machine running Spinnaker.
#              sshPrivateKeyFilePath: sshKey    # (Secret). Path to the ssh private key in PEM format. File needs to be present on the machine running Spinnaker.
#              sshPrivateKeyPassphrase: xyz     # (Secret). Passphrase for encrypted private key.
#              sshKnownHostsFilePath: hosts     # (Secret). File containing the known and trusted SSH hosts. File needs to be present on the machine running Spinnaker.
#              sshTrustUnknownHosts: false      # Setting this to true allows Spinnaker to authenticate with unknown hosts.
    profiles:
      deck:  # Enable this setting under core_config/patch-deck.yml
      #   # Enables terraformer UI
        settings-local.js: |
          window.spinnakerSettings.feature.terraform = true;
      gate:
        proxies:
          - id: terraform
            uri: http://spin-terraformer:7088
            methods:
              - GET
      terraformer:
        # Terraformer named profiles, for supplying credentials to terraformer
        profiles:
          - name: aws-with-session-tokens
            variables:
              - kind: static
                options:
                  name: AWS_ACCESS_KEY_ID
                  value: XXXXXXXXXXXXXXXXXXXX
              - kind: static
                options:
                  name: AWS_SECRET_ACCESS_KEY
                  value: encrypted:k8s!n:spin-secrets!k:aws-secret-key
              - kind: static
                options:
                  name: AWS_SESSION_TOKEN
                  value: encrypted:k8s!n:spin-secrets!k:aws-session-token
          - name: spinnaker
            variables:
              - kind: aws
                options:
                  accessKeyId: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.aws.accessKeyId
                  secretAccessKey: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.aws.secretAccessKey
          - name: armory-spinnaker-managing-account
            variables:
              - kind: aws
                options:
                  accessKeyId: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.aws.dev.accessKeyId
                  secretAccessKey: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:armory.aws.dev.secretAccessKey
                  assumeRole: arn:aws:iam::025179128306:role/PSSpinnakerManagedRole
        # Used for connecting to an external Redis instance
        redis:
          baseUrl: "redis://spinnaker.hsjng8.ng.0001.usw2.cache.amazonaws.com:6379"
#          password: "password"

    service-settings:
      terraformer:
        kubernetes:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

# # used for adding gcp credentials for terraform
# # first create a secret with your gcp-credentials.json e.g. `kubectl create secret generic gcp-creds --from-file gcp-credentials.json`
#   kustomize:
#     terraformer:
#       deployment:
#         patchesJson6902: |
#           - op: add
#             path: /spec/template/spec/containers/0/volumeMounts/-
#             value:
#               mountPath: /opt/spinnaker/creds
#               name: gcp-creds
#           - op: add
#             path: /spec/template/spec/volumes/-
#             value:
#               name: gcp-creds
#               secret:
#                 secretName: gcp-creds
#           - op: add
#             path: /spec/template/spec/containers/0/env/-
#             value:
#               name: GOOGLE_APPLICATION_CREDENTIALS
#               value: /opt/spinnaker/creds/gcp-credentials.json
