#-----------------------------------------------------------------------------------------------------------------
# Example configuration for enabling dinghy (pipelines as code stored in source control).
#
# Feature documentation: https://docs.armory.io/docs/spinnaker/using-dinghy/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      armory:
        dinghy:
          enabled: true
          templateOrg: DigitalOnUs                                      # SCM organization or namespace where application and template repositories are located
          templateRepo: dinghyfile-example                           # SCM repository where module templates are located
          #           fiatUser: dinghy-sa                                     # Service account for dinghy to use, required if fiat is enabled
          # --- github settings
          githubToken: encrypted:s3!r:us-west-2!b:dou-armory-spinnaker-secrets!f:spinnaker-secrets.yml!k:dou.github.token # (Secret). GitHub token
          githubEndpoint: https://api.github.com                   # (Default: https://api.github.com) Github API endpoint. Useful if you’re using Github Enterprise
          # --- bitbucket/stash settings
          #          stashUsername: stash_user                                     # Stash username
          #          stashToken: encrypted:k8s!n:spin-secrets!k:bitbucket-password # (Secret). Stash token
          #          stashEndpoint: https://my-endpoint                            # Stash API endpoint. If you're using Bitbucket Server, update the endpoint to include the api e.g. https://your-endpoint-here.com/rest/api/1.0
          # --- gitlab settings
          #          gitlabToken: encrypted:k8s!n:spin-secrets!k:gitlab-token # (Secret). GitLab token
          #          gitlabEndpoint: https://my-endpoint                      # GitLab endpoint
          #          notifiers:
          #            slack:
          #              enabled: true       # Whether or not Slack notifications are enabled for dinghy events
          #              channel: my-channel # Slack channel where notifications will be sent to

    profiles:
      dinghy:
        #        parserFormat: hcl   # Must be one of: hcl, yaml, json. Use an alternate format for dinghy files.
        # Custom branch configuration (see https://docs.armory.io/docs/spinnaker/install-dinghy/#custom-branch-configuration)
        #        repoConfig:
        #          - branch: some_branch
        #            provider: github  # Must be one of: github, bitbucket-cloud, bitbucket-server
        #            repo: my-bitbucket-repository
        # Use an external redis instance (recommended for production)
        redis:
          baseUrl: "redis://spinnaker.hsjng8.ng.0001.usw2.cache.amazonaws.com:6379"
          #password: encrypted:k8s!n:spin-secrets!k:redis-password
