#-----------------------------------------------------------------------------------------------------------------------
# Quick Start recipe
#
# Self contained Spinnaker installation with no external dependencies and no additional configuration needed.
# Not for production use.
#
# Features:
# - One Kubernetes account (Spinnaker's own cluster) for deployment targets
# - One dockerhub account for public repositories
# - Spinnaker authentication disabled
# - Spinnaker exposed out of the cluster using 2 public Kubernetes service load balancers
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker and all its infrastructure will be installed.
# NOTE: If changed, also change it in all ClusterRoleBinding namespace references.
namespace: spinnaker

resources:
  - spinnakerservice.yml             # (Mandatory). Base spinnaker manifest
  - accounts/kubernetes/spin-sa.yml  # Kubernetes service account needed by patch-kube.yml

patchesStrategicMerge:
  - persistence/patch-s3.yml
  - persistence/patch-redis.yml
  - persistence/patch-sql-clouddriver.yml  # MySQL compatible database
  - persistence/patch-sql-front50.yml
  - persistence/patch-sql-orca.yml

  # - services/clouddriver/patch-clouddriver-artifact-id.yml # override docker image for clouddriver
  # - services/fiat/patch-fiat-artifact-id.yml # override docker image for fiat, Temporary fix as https://github.com/spinnaker/fiat/pull/907
  # - services/front50/patch-front50-artifact-id.yml # override docker image for front50
  # - services/orca/patch-orca-artifact-id.yml # override docker image for orca

  - expose/patch-lb-aws.yml             # Expose spinnaker through AWS load balancer
  - accounts/kubernetes/patch-kube.yml  # Kubernetes accounts
  - accounts/docker/patch-dockerhub.yml # Docker accounts
  - accounts/git/patch-bitbucket.yml # Bitbucket accounts
  # - accounts/cloudfoundry/patch-cloudfoundry.yml
  - accounts/aws/patch-aws.yml
  # - security/patch-fiat-create-app-roles.yml
  - security/patch-github.yml

  # Armory features
  - armory/patch-terraformer.yml
  - armory/patch-dinghy.yml
  # - plugins/external-accounts/patch-external-accounts-plugin-sidecar.yml # Enable external-accounts plugin
  # - plugins/iam-auth/patch-iam-auth-clouddriver.yml
  # - plugins/iam-auth/patch-iam-auth-front50.yml
  # - plugins/iam-auth/patch-iam-auth-orca.yml
  # - plugins/iam-auth/persistence/patch-sql-clouddriver.yml  # MySQL 5.7 Aurora compatible database
  # - plugins/iam-auth/persistence/patch-sql-front50.yml # MySQL 5.7 Aurora compatible database
  # - plugins/iam-auth/persistence/patch-sql-orca.yml # MySQL 5.7 Aurora compatible database