version: '3.5'
services:
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init_db:/docker-entrypoint-initdb.d

  catalog:
    build: catalog-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  user:
    build: user-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  cart:
    build: cart-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - catalog
      - user

  api-gateway:
    image: nginx:1.15.0
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - catalog
      - user
      - cart

