version: '3'

#docker-compose -p "rb-backend" up -d
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: DB-MySQL-Users
    environment:
      MYSQL_DATABASE: users_db

      MYSQL_USER: dou
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 443
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 443:443
    expose:
      # Opens port 443 on the container
      - '443'

