apiVersion: v1
kind: Pod
metadata:
  name: "elasticsearch"
  labels:
    service: "elasticsearch"
    name: "devops"
  namespace: "devops"
spec:
  volumes:
  - name: elasticsearch-data
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /elasticsearch_data/_data
  containers:
  - name: elasticsearch
    image: elasticsearch:2.1.1
    args:
    - elasticsearch
    - "-Des.network.host=0.0.0.0"
    ports:
    - containerPort: 9200
      protocol: TCP
    volumeMounts:
    - name: elasticsearch-data
      mountPath: "/usr/share/elasticsearch/data"
