apiVersion: v1
kind: Pod
metadata:
  name: "kibana"
  labels:
    service: "kibana"
    name: "devops"
  namespace: "devops"
spec:
  containers:
  - name: kibana
    image: kibana:4.3.1
    args:
    - kibana
    ports:
    - containerPort: 5601
      protocol: TCP
    env:
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200