apiVersion: v1
kind: Pod
metadata:
  name: "sonar"
  labels:
    service: sonar
    name: "devops"
  namespace: "devops"
spec:
  volumes:
  - name: "sonar-data"
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /sonar_data/_data
  - name: "sonar-extensions"
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /sonar_extensions/_data
  - name: "sonar-logs"
    nfs:
     server: fs-da935a73.efs.us-west-2.amazonaws.com
     path: /sonar_logs
  containers:
  - name: sonar
    image: accenture/adop-sonar:0.2.0
#    command: ["apt update"]
#    command: ["apt install nfs-common"]
    env:
#    - name: 'dependency:container'
#      value: '=sonar-mysql'
    - name: "SONARQUBE_JDBC_USERNAME"
      value: "sonar"
    - name: "SONARQUBE_JDBC_PASSWORD"
      value: "sonar"
    - name: "LDAP_URL"
      value: "ldap://ldap:389"
    - name: "LDAP_BIND_DN"
      value: "cn=admin,dc=ldap,dc=example,dc=com"
    - name: "LDAP_BIND_PASSWORD"
      value: "e5fdb71de4379485"
    - name: "LDAP_USER_BASE_DN"
      value: "ou=people,dc=ldap,dc=example,dc=com"
    - name: "LDAP_USER_REQUEST"
      value: "(&(objectClass=inetOrgPerson)(uid={login}))"
    - name: "LDAP_USER_REAL_NAME_ATTRIBUTE"
      value: "displayName"
    - name: "LDAP_USER_EMAIL_ATTRIBUTE"
      value: "mail"
    - name: "LDAP_GROUP_BASE_DN"
      value: "ou=groups,dc=ldap,dc=example,dc=com"
    - name: "LDAP_GROUP_REQUEST"
      value: "(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
    - name: "LDAP_GROUP_ID_ATTRIBUTE"
      value: "cn"
    - name: "SONARQUBE_JDBC_URL"
      value: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
    ports:
    - name: sonar-port
      containerPort: 9000
    volumeMounts:
    - name: "sonar-data"
      mountPath: "/opt/sonarqube/data"
    - name: "sonar-extensions"
      mountPath: "/opt/sonarqube/extensions"
    - name: "sonar-logs"
      mountPath: "/opt/sonarqube/logs"
          
