filebeat:
  inputs:
    - type: log
      paths:
        - /var/log/rabbitmq/*.log
        - /var/log/consul.log
      tags: [rabbitmq]

  processors:
     - drop_fields:
       fields: ["host"]
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash.{{ env }}.corvesta.net:5044"]
