AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 module Definition'
Parameters:
  ParameterVersion:
    Type: Number
    Description: 'Version'
  ParameterAMI:
    Description: 'AMI base image'
    Type: AWS::EC2::Image::Id
  ParameterInstanceType:
    Type: String
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - m4.large
    - m5.large
    - m4.xlarge
    - m5.xlarge
    - m4.2xlarge
    - m5.2xlarge
    - c4.large
    - c5.large
    - c4.xlarge
    - c5.xlarge
    - c4.2xlarge
    - c5.2xlarge
    - r4.large
    - r5.large
    - r4.xlarge
    - r5.xlarge
    - r4.2xlarge
    - r5.2xlarge
  ParameterInstanceProfile:
    Description: 'Instance profile'
    Type: String
  ParameterSubnet:
    Description: 'Subnet for the instance'
    Type: String
  ParameterSecurityGroup:
    Description: 'Security group for the instance'
    Type: String
  ParameterKeyPair:
    Description: 'Key pair to attach to the instance'
    Type: String
  ParameterInstanceName:
    Description: 'Instance name'
    Type: String
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ParameterAMI
      InstanceType:
        Ref: ParameterInstanceType
      IamInstanceProfile:
        Ref: ParameterInstanceProfile
      SubnetId:
        Ref: ParameterSubnet
      SecurityGroupIds:
      - Ref: ParameterSecurityGroup
      KeyName:
        Ref: ParameterKeyPair
      Tags:
      - Key: Name
        Value:
          Ref: ParameterInstanceName
      - Key: "Version"
        Value:
          Ref: ParameterVersion