AWSTemplateFormatVersion: '2010-09-09'
Description: 'Workspace Module'
Parameters:
  ParameterVersion:
    Type: Number
    Description: 'Version'
  ParameterDirectoryName:
    Description: 'AD Name'
    Type: String
  ParameterDirectoryServiceType:
    Type: String
    AllowedValues:
    - Microsoft AD,Standard
    - Microsoft AD,Enterprise
  ParameterNetBiosName:
    Description: 'Short name for the AD'
    Type: String
  ParameterVPCId:
    Description: 'VPC Id'
    Type: String
  ParameterSubnetId1:
    Description: 'First subnet id for the AD'
    Type: String
  ParameterSubnetId2:
    Description: 'Second subnet id for the AD'
    Type: String
  ParameterAdministratorPassword:
    NoEcho: 'true'
    Description: 'Administrator Password'
    Type: String
  ParameterBundleId:
    Type: String
    Description: 'Select the bundle that should be deployed'
  ParameterDirectoryId:
    Type: String
    Description: Enter the Directory ID for the WorkSpace (Directory Services or AD Connector)
  ParameterUser:
    Type: String
    Description: Enter the username who will use the WorkSpace
  ParameterEncryptionKey:
    Type: String
    Description: KMS encryption key to encrypt
Resources:
  ResourceSimpleAD:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      Size:
        Fn::Select:
        - '1'
        - Fn::Split:
          - ","
          - Ref: ParameterDirectoryServiceType
      Name:
        Ref: ParameterDirectoryName
      Password:
        Ref: ParameterAdministratorPassword
      ShortName:
        Ref: ParameterNetBiosName
      VpcSettings:
        VpcId:
          Ref: ParameterVPCId
        SubnetIds:
        - Ref: ParameterSubnetId1
        - Ref: ParameterSubnetId2
  ResourceWorkspace:
    Type: AWS::WorkSpaces::Workspace
    Properties:
      BundleId:
        Ref: ParameterBundleId
      DirectoryId:
        Ref: ParameterDirectoryId
      UserName:
        Ref: ParameterUser
      RootVolumeEncryptionEnabled: 'true'
      UserVolumeEncryptionEnabled: 'true'
      VolumeEncryptionKey: !Ref ParameterEncryptionKey
      Tags:
      - Key: "Version"
        Value:
          Ref: ParameterVersion