name: Binary Tests

on:
  repository_dispatch:
    types: [build-complete]
  watch:
    types: [started]

jobs:
  test_mac_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Mac Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          DWARF_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          OKTA_SSO_USER: ${{ secrets.OKTA_SSO_USER }}
          OKTA_SSO_PASSWORD: ${{ secrets.OKTA_SSO_PASSWORD }}
          OKTA_EMBED_URL: ${{ secrets.OKTA_EMBED_URL }}
          OKTA_MFA_SECRET: ${{ secrets.OKTA_MFA_SECRET }}
          DWARF_DISABLE_METRICS: true
          DWARF_DISABLE_VERSION_CHECK: true
          TERM: xterm-256color
          TERMINFO: /etc/terminfo
        run: |
          dest="s3://dwarf-website/releases/cli/unstable/darwin/dwarf.zip"
          aws s3 cp $dest .
          unzip dwarf.zip
          cd dwarf
          export PATH="$PATH:$(PWD)"
          cd ../src

          pip install -r requirements.txt
          pip3 install -r requirements-test.txt

          echo "Testing MAC binary as okta user"
          python run_tests.py okta

  test_linux_binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Linux Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          DWARF_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          DWARF_DISABLE_METRICS: true
          DWARF_DISABLE_VERSION_CHECK: true
          TERM: linux
          TERMINFO: /etc/terminfo
        run: |
          dest="s3://dwarf-website/releases/cli/unstable/linux/dwarf.zip"
          aws s3 cp $dest .
          unzip dwarf.zip
          cd dwarf
          export PATH="$PATH:$(pwd)"
          cd ../src

          pip install -r requirements.txt
          pip3 install -r requirements-test.txt

          echo "Testing MAC binary as okta user"
          python run_tests.py bastion

  test_windows_binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Windows Binary Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          DWARF_DISABLE_KEYRING: true
          OVERRIDE_KEYRING: true
          DWARF_DISABLE_METRICS: true
          DWARF_DISABLE_VERSION_CHECK: true
        shell: bash
        run: |
          dest="s3://dwarf-website/releases/cli/unstable/windows/dwarf.zip"
          aws s3 cp $dest .
          unzip dwarf.zip
          cd dwarf
          export PATH="$PATH:$(PWD)"
          cd ../src

          dwarf --version

  emit_binary_tests_complete:
    runs-on: ubuntu-latest
    needs:
      - test_mac_binary
      - test_linux_binary
      - test_windows_binary
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: DigitalOnUs/dwarf
          event-type: binary-tests-complete
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
