name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft, ready_for_review]
    branches:
      - master
      - main

jobs:
  tffmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Format Recursive Check
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: false
