# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_download_insecure = true
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  groups = {

     "iidk-consul-aws" => "192.168.56.0"
  }

  groups.each_with_index do |(machine_name, machine_ip), index|
    config.vm.define "#{machine_name}" do |machine|
      machine.vm.synced_folder "~/.aws", "/root/.aws"
      machine.vm.hostname = "#{machine_name}"
      machine.vm.network "private_network", ip: "#{machine_ip}"

      #machine.vm.network "forwarded_port",guest: 8500, host: 8500
      #machine.vm.network "forwarded_port",guest: 5500, host: 5500
      #machine.vm.network "forwarded_port",guest: 8080, host: 8081
      #machine.vm.network "forwarded_port",guest: 5600, host: 5600
      #machine.vm.network "forwarded_port",guest: 15672, host: 15672
      #machine.vm.network "forwarded_port",guest: 5432, host: 5432


      # First, install python
      config.vm.provision "shell" do |s|
        s.inline = "apt-get update -y && apt-get install -y python"
        #s.inline = "keytool -importcert -file /etc/ssl/certs/CASERVER-CA.pem -keystore /usr/lib/jvm/java-8-openjdk-amd64//jre/lib/security/cacerts -trustcacerts -noprompt -storepass changeit -alias fewknow"
      end
      # Only execute the Ansible provisioner,
      # when all the machines are up and ready.
      provisioner = Vagrant::Util::Platform.windows? ? :guest_ansible : :ansible

      if index == groups.size - 1
        machine.vm.provision provisioner do |ansible|
          ansible.playbook       = "playbooks/site.yml"
          ansible.limit          = "all" # or only "nodes" group, etc.
          ansible.inventory_path = "inventories/vagrant"
          ansible.compatibility_mode = "2.0"
          ansible.galaxy_role_file = "playbooks/iidk-consul-aws-requirements.yml"
          ansible.galaxy_roles_path = "./galaxy/roles"
          ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force -vvvv"
          # ansible.start_at_task = "Install datadog java client"
          # ansible.verbose = "-vvvv"
          # ansible.ask_vault_pass = true
          # ansible.tags = ["test"]
        end
      end
    end
  end
end
