AWSTemplateFormatVersion: '2010-09-09'
Description: 'Subnet Module definition'
Parameters:
  ParameterVersion:
    Type: Number
    Description: 'Version'
  ParameterSubnetServers:
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(3[0-2]|[1-2][0-9]|[0-9]))$"
    Description: 'Enter the subnet for EC2 instances'
  ParameterAvailabilityZone:
    Type: String
    Description: 'Availability Zone for the deployment'
  ParameterPublicIP:
    Type: String
    Description: 'Is public or private'
  ParameterSubnetName:
    Type: String
    Description: 'Name for your public subnet'
  ParameterVPCId:
    Type: String
    Description: 'VPC Id to associate the subnet'
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ParameterVPCId
      CidrBlock:
        Ref: ParameterSubnetServers
      AvailabilityZone:
        Ref: ParameterAvailabilityZone
      MapPublicIpOnLaunch: 
        Ref: ParameterPublicIP
      Tags:
      - Key: Name
        Value:
          Ref: ParameterSubnetName
      - Key: "Version"
        Value:
          Ref: ParameterVersion
Outputs:
  SubnetId:
    Value: !GetAtt Subnet.SubnetId